# Generated by Django 2.0.3 on 2018-03-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180329_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='posts.Subcategory', verbose_name='Категория'),
        ),
    ]
