# Generated by Django 2.0.3 on 2018-03-29 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180329_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='posts.Subcategory', verbose_name='Категория'),
        ),
    ]
