# Generated by Django 2.0.3 on 2018-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Код подтверждения номера'),
        ),
    ]
