# Generated by Django 2.0.3 on 2018-03-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20180314_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True, verbose_name='Код подтверждения номера'),
        ),
    ]
