# Generated by Django 2.0.3 on 2018-03-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_auto_20180314_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
