# Generated by Django 2.0.3 on 2018-03-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0005_auto_20180314_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='Фото'),
        ),
    ]
